# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'udp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from threading import Thread
from PyQt5.QtCore import QDate, Qt
import time
import threading
import socket
import sqlite3
import time
import datetime
import sys
import glob
import serial


class Ui_MainWindow(object):
    def udp_(self):
        self.timer = QtCore.QTimer()
        self.timer.setInterval(100)
        try:
            self.timer.timeout.connect(self.readData)
        except:
            print("readData error")
        self.timer.start() 
    def readData(self):
        print('hello')
        HOST = 'localhost' # Thiết lập địa chỉ address
        PORT = 8000 # Thiết lập post lắng nghe
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM) # cấu hình kết nối        
        s.bind((HOST, PORT)) # lắng nghe
        s.listen(1) # thiết lập tối ta 1 kết nối đồng thời
        conn,   addr = s.accept() # chấp nhận kết nối và trả về thông số
        with conn:
            try:
                # in ra thông địa chỉ của client
                print('Connected by', addr)
                while True:
                    # Đọc nội dung client gửi đến
                    data = conn.recv(1024)
                    # In ra Nội dung 
                    print(data)
                    # Và gửi nội dung về máy khách
                    conn.sendall(b'Hello client')
                    if not data: # nếu không còn data thì dừng đọc
                        break
            finally:
                s.close() # đóng socket     
                   
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(441, 291)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 160, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 70, 47, 13))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 120, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 441, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        t1 = Thread(target = self.udp_())
        t1.start()


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
