# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import threading
import time
import datetime
import serial
# from jwt import python_jwt
from firebase import firebase

from threading import Thread
from PyQt5.QtCore import QDate, Qt
data1=serial.Serial('COM10',baudrate=9600,timeout=0.1)
firebase = firebase.FirebaseApplication('https://hellodatn-default-rtdb.asia-southeast1.firebasedatabase.app/',None)



class Ui_MainWindow(object):
    def readData(self):
        if data1.in_waiting >0:
            data = data1.readline()
            data = data.decode('utf-8')
            print(data)   
            self.lab_hoagle.setText("Nhiệt độ: " + data)
            # result = firebase.post('data', data)
            # result = firebase.put('phòng 1','nhiệt độ',data)
    def read_interval(self):
        self.timer = QtCore.QTimer()
        self.timer.setInterval(100)
        self.timer.timeout.connect(self.readData)
        self.timer.start()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(453, 279)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lab_hoagle = QtWidgets.QLabel(self.centralwidget)
        self.lab_hoagle.setGeometry(QtCore.QRect(150, 40, 180, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lab_hoagle.setFont(font)
        self.lab_hoagle.setObjectName("lab_hoagle")
        self.butt_ok = QtWidgets.QPushButton(self.centralwidget)
        self.butt_ok.setGeometry(QtCore.QRect(180, 160, 75, 23))
        self.butt_ok.setObjectName("butt_ok")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.butt_ok.clicked.connect(self.senddata)
        t1 = Thread(target = self.read_interval())
        t1.start()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def senddata(self):   
        helloz="a"     
        data1.write(helloz.encode())
        print("HELLO")

    # def change__(self):
    #     tt = self.lab_hoagle.text()
    #     if tt == "Hoàng Lê":
    #         self.lab_hoagle.setText("Sáng")
    #     else:
    #         self.lab_hoagle.setText("Tắt")
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_hoagle.setText(_translate("MainWindow", "Hoàng Lê"))
        self.butt_ok.setText(_translate("MainWindow", "OKAY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
